### ISSUE TITLE
[Sandbox] Cozystack

### ISSUE THREAD

**Issue by kvaps** [cncf/sandbox#87] opened 2024-02-14 10:45 UTC
### Application contact emails

andrei.kvapil@aenix.io, timur.tukaev@aenix.io, george.gaal@aenix.io

### Project Summary

Cozystack is an open-source PaaS platform and framework for building clouds

### Project Description

With Cozystack, you can transform your bunch of servers into an intelligent system with a simple REST API for spawning Kubernetes clusters, Database-as-a-Service, virtual machines, load balancers, HTTP caching services, and other services with ease.

You can use Cozystack to build your own cloud or to provide a cost-effective development environments.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/aenix-io

### Project repo URL in scope of application

https://github.com/aenix-io/cozystack

### Additional repos in scope of the application

https://github.com/aenix-io/talos-bootstrap/

### Website URL

https://cozystack.io/

### Roadmap

https://github.com/orgs/aenix-io/projects/2

### Contributing Guide

https://github.com/aenix-io/cozystack/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/aenix-io/cozystack/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/aenix-io/cozystack/blob/main/ADOPTERS.md

### Contributing or Sponsoring Org

https://aenix.io/

### Maintainers file

https://github.com/aenix-io/cozystack/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We're startup and group of entusiasts which decided to go by the way of standardization.
Our platform is based on many other CNCF projects and provides a turn-key solution which is easy to install and use.
We want to keep this standardization as much as possible, we believe that open-source is the only way to achieve this.

Being a CNCF member, will allow us to show people our intention to remain standard and always free.

We adopt Kubernetes, Talos Linux, KubeVirt, Kamaji, FluxCD, Cluster API, Cert-Manager, Piraeus, Kube-OVN, Cilium, MetalLB, among others. We contribute a lot to these projects. We are keen to collaborate closely with them.
It would be nice to join a common ecosystem build by CNCF.

Since we self-bootstrapped we have no any profit yet, we need a help with promotion and various opportunities like both and lighting talks on KubeCon to let the people know about our project and attact the sponsors and external contributors.

### Benefit to the Landscape

One of our motos: "Collaborate, not compete"

We are proud of our community and closely interact with projects around it. Thus if a feature being developed for the platform could be useful to a upstream project, it should be contributed to upstream project, rather than being implemented within the platform.

Being a CNCF member will help users of other CNCF projects with adoption of their technologies as they could provide a ready product and real-world example how it can be used.

Also we can organize a people to make a beatiful things together, for example etcd-operator is one of this community-driven project
https://github.com/cncf/sandbox/issues/91

### Cloud Native 'Fit'

We believe that our project will help various cloud-providers to build their infrastructure based on modern cloud-native principles.

The project goal is that you can manage your bare-metal infrastracture using cloud native approaches:

- You can bootstrap your physical server using the declarative way, just by applying an Yaml file on it.
- You can use beatiful Kubernetes API instead of dificult assincronious APIs on OpenStack.

### Cloud Native 'Integration'

We use a lot of CNCF projects and build a single ecosystem around them:

<s>

#### [**Talos Linux**](https://github.com/siderolabs/talos)

Using Talos Linux as the base layer for the platform allows to strictly limit the technology stack and make the system stable as a rock.

Talos Linux has no moving parts, no traditional package manager, no file structure, and no ability to run anything except Kubernetes containers.  The base layer of the platform includes the latest version of the kernel, all the necessary kernel modules, container runtime and a Kubernetes-like API for interacting with the system.

Updating the system is done by rewriting the image “as is” entirely onto the hard drive.

</s>

#### **[Kubernetes](https://github.com/kubernetes/kubernetes) and [etcd](https://github.com/etcd-io/etcd)**

Kubernetes has already become a kind of de facto standard for managing server workloads.

Our platform is Kubernetes-based and provides managed Kubernetes service that allows you to create full-featured Kubernetes clusters on demand. For each cluster, a separate managed control-plane and virtual compute nodes are created.

The control-plane is powered by [**Kamaji**](https://github.com/clastix/kamaji) project and separate [**etcd**](https://etcd.io/) cluster for backend. We utilize [**Cluster API**](https://github.com/kubernetes-sigs/cluster-api) for spawnging tenant Kubernetes clusters.

#### [**KubeVirt**](https://github.com/kubevirt/kubevirt)

KubeVirt is a project started by global industry leaders with a common vision to unify Kubernetes and a desire to introduce it to the world of virtualization. KubeVirt extends the capabilities of Kubernetes by providing convenient abstractions for launching and managing virtual machines, as well the all related entities such as snapshots, presets, virtual volumes, and more.

#### **[Helm](https://github.com/helm/helm) and [FluxCD](https://github.com/fluxcd/flux2)**

Each package in the platform consists of a set of YAML files combined into Helm chart. Therefore, anyone with some familiarity with Kubernetes primitives can modify or expand the platform. Delivery of packages to the system is handled by FluxCD, a well-known and widely used tool in the community.

FluxCD is the main system used to build distribution. FluxCD is used for three different cases:
- to deliver and setup basic system platform components 
- to let users setup their applications into the platform
- to deliver and install components into user's Kubernetes clusters

#### [**Kube-OVN**](https://github.com/kubeovn/kube-ovn)

Kube-OVN is a free implementation of virtual network fabric for Kubernetes based on Open vSwitch technology. With OVN, you get a robust and functional virtual network that ensures reliable isolation between tenants and provides floating addresses for virtual machines.

This enables seamless integration with other clusters and customer network services.

#### [**Cilium**](https://github.com/cilium/cilium/)

Utilizing Cilium in conjunction with OVN enables the most efficient and flexible network policies, along with a productive services network in Kubernetes, leveraging an offloaded Linux network stack featuring the cutting-edge eBPF technology.

#### [**MetalLB**](https://github.com/metallb/metallb)

MetalLB is the default load balancer for Cozystack; with its help, the services obtain public addresses that are accessible from outside the cluster network.

#### [**Piraeus**](https://github.com/piraeusdatastore/piraeus-operator)

DRBD is the fastest replication block storage running right in the Linux kernel. When DRBD only deals with data replication, time-tested technologies such as LVM or ZFS are used for securely store the data. The DRBD kernel module is included in the mainline Linux kernel and has been used to build fault-tolerant systems for over a decade.

DRBD is managed by LINSTOR privided by piraeus-operator. It provides an orchestation system integrated to Kubernetes which provides the management layer for creating virtual volumes based on DRBD.

<s>

#### [**Kubeapps**](https://github.com/vmware-tanzu/kubeapps)

While the primary goal of the platform is to provide a beautiful API, it also has a dashboard for deploying applications, this dashboard is based on Kubeapps. It facilitates a quick dive into the platform and provides a visual demonstration of its capabilities.

The Web UI facilitates a quick dive into the platform and provides a visual demonstration of its capabilities.

</s>

#### [**CloudNativePG**](https://github.com/cloudnative-pg/cloudnative-pg)

Nowadays PostgreSQL is the most popular relational database. Its platform-side implementation involves a self-healing replicated cluster, managed with the increasingly popular CloudNativePG operator within the community.

##### [**Strimzi**](https://github.com/strimzi/strimzi-kafka-operator)

Strimzi provides a way to run an [Apache Kafka®](https://kafka.apache.org/) cluster on [Kubernetes](https://kubernetes.io/) or [OpenShift](https://www.openshift.com/) in various deployment configurations. See our [website](https://strimzi.io/) for more details about the project.

#### [**VMware Tanzu**](https://tanzu.vmware.com/tanzu)

VMware Tanzu is a proprietary solution for creating Kubernetes clusters.
Our platform, however, is fully based on open-source and free technologies.

Additionally, to launch control planes, you don't need separate VMs, and we offer more services.

#### [**Rancher**](https://www.rancher.com/)

Rancher can offer similar functionality but operates within its own ecosystem, offering a different value proposition.
While Rancher is more of a Kubernetes distribution, Cozystack is akin to a cloud platform.

### Landscape

No, we just started :)

### Business Product or Service to Project separation

Cozystack is a free project which is more likely a tool developed for our needs.

Ænix supervises the development and provides paid support. This paid support includes all types of assistance, including consultations, development of missing features, design, assistance with installation, and integration.

### Project presentations

presentation: https://www.slideshare.net/slideshows/cozystack-free-paas-platform-and-framework-for-building-clouds/266662388
video: https://www.youtube.com/watch?v=24i9wIsJHGE

* KCD: https://youtu.be/wBKrGVWbdcI
* TIC: https://youtu.be/9CIMTum9bTA

### Project champions

- Andrei Kvapil @kvaps
- Timur Tukaev @tym83
- George Gaál @gecube

**Comment by amye** [comment] 2024-02-14 16:03
You might want to amend this, there are several non-CNCF projects listed 😂

**Comment by kvaps** [comment] 2024-02-14 17:34
Well, that's actually true.

I just double checked the information, and I found that:


- **Talos Linux** applied for CNCF Sandbox on December 2022, didn't go through:

  ```
  Talos Linux - reapply with more technical details + clarification
  around how this connects with the cloud native ecosystem
  ```

  source: https://lists.cncf.io/g/cncf-toc/message/7743

- **CloudNativePG** are mentioned on [their website](https://cloudnative-pg.io/documentation/1.22/) that they are submitted for CNCF Sandbox in April 2022:
  ```
  CloudNativePG was originally built by EDB, then released open source under Apache License 2.0 and submitted for CNCF Sandbox in April 2022
  ```

  But I have not found any infromation on the [official CNCF website](https://www.cncf.io/sandbox-projects/)

  Can anyone confirm or deny this information?

- **kubeapps** is just mentioned [multiple times](https://www.google.com/search?q=kubeapps+site%3Acncf.io) on CNCF website, so it made me confusing

I have to check the information better. Thank you for pointing this out.

**Comment by kvaps** [comment] 2024-02-21 10:59
Hey there 👋 

I just prepared a blog-post about Cozystack for kubernetes.io: https://github.com/kubernetes/website/pull/45240

**Comment by joshgav** [comment] 2024-02-21 15:55
@amye this should probably be tagged for TAG App Delivery (and WG Platforms) too. Thanks!

**Comment by kevin-wangzefeng** [comment] 2024-04-19 04:55
Please ignore the status change above; that was caused by my mistouch while accessing the website on my mobile browser.

**Comment by TheFoxAtWork** [comment] 2024-07-22 21:21
@lianmakesthings - Does TAG App Delivery have a recommendation for this project?
@leecalcote @nicholasjackson @zachbutcher - Does TAG Network have a recommendation for this project?

**Comment by lianmakesthings** [comment] 2024-07-23 08:30
Hi all, I was checking our notes and couldn't find a reference to cozystack. Was this project ever presented to the TAG App Delivery? If yes, would you be able to share the date?

**Comment by kvaps** [comment] 2024-07-23 08:39
@lianmakesthings
Hi, we have not presented this project to any TAG, but we would be happy to do so.
Could you please guide how to properly schedule a meet with TAG to perform this?

**Comment by kvaps** [comment] 2024-07-23 08:51
I just found tomorrow will be [TAG App Delivery - General Meeting](https://community.cncf.io/events/details/cncf-tag-app-delivery-presents-tag-app-delivery-general-meeting-2024-07-24/). Is that correct place for making presentation?

**Comment by lianmakesthings** [comment] 2024-07-23 09:07
Hi @kvaps 
yes indeed our next meeting is tomorrow and there is no other project on the agenda so you're welcome to present Cozystack. I would recommend a brief presentation, no longer than 20 minutes, so there is ample time for questions and discussion. Following the presentation, we will gather feedback and give our recommendation to the TAG.

Here is the link to tomorrow's meeting: https://zoom-lfx.platform.linuxfoundation.org/meeting/98590236563?password=b0335b64-4162-4499-bb61-ff2c7dec2724
If you sign up on openprofile.dev, the recording will be made available to you immediately on the LFX platform, which you are also free to share.

Please let me know if you have any more questions. Otherwise, see you tomorrow!

**Comment by roberthstrand** [comment] 2024-07-29 11:13
For transparency I would just like to mention that I will be working on reviewing this project for TAG App Delivery. We will have Cozystack on our August 7th meeting, and potentially at the next Platforms WG meeting as well.

**Comment by jberkus** [comment] 2024-08-02 00:41
Question, unrelated to the TAG-CS review:  given that Talos Linux did not become part of the CNCF, would you still be contributing the talos-bootstrap repository?

**Comment by kvaps** [comment] 2024-08-02 06:12
> Question, unrelated to the TAG-CS review: given that Talos Linux did not become part of the CNCF, would you still be contributing the talos-bootstrap repository?

Yes, we're going to add this functionality into Talm configuration manager
https://github.com/aenix-io/talm


We like Talos Linux and are happy to use it for our customers. But we don't want to be dependent on Talos Linux alone, we want to support various distributions as well.

**Comment by kvaps** [comment] 2024-08-02 06:18
As about documentation, it's slightly oudated. We'll fix it soon. We have more contributors and weekly meetings established with 4-7 person's visiting it every time. All of them from various companies and countries 

https://youtube.com/playlist?list=PLEIgpkcPkMHaXqndo8iMMLS64p4sBkHPg&si=DOJ7mjA9MSEhJBYS

**Comment by roberthstrand** [comment] 2024-08-12 13:30
Hello again @kvaps, sorry for the late post here.

A couple of follow-up questions after the TAG presentation. Good variation across the board here, as I purposely choose questions that expands on what I learned from your presentation.

1. Explain the design principles and best practices the project is following. 
2. Could you describe the project’s release processes, including major, minor and patch releases.
3. Define any specific service dependencies the project relies on in the cluster.
4. Describe the project’s dependency lifecycle policy for each repo.
5. Describe all of the signals the project is using or producing, including logs, metrics, profiles and traces. Please include supported formats, recommended configurations and data storage.

**Comment by kvaps** [comment] 2024-08-12 16:56
Hi @roberthstrand, thank you for your questions,

> Explain the design principles and best practices the project is following.

The core value of the Cozystack is to provide ready configuration for all the system and user components.
The main focus for now is to build PAAS platform that is simple to install and ready to use by service providers.

Thanks to Kubernetes all the components of the platform are standartized and unified.

Thanks to Talos Linux the system configuration is fully atomic and managed by single YAML file format.
We ship all the kernel modules and system configuration together with the platform.

In another words we just removed the OS layer operations to avoid system bugs and human mistakes by strict APIs of Kubernetes and Talos Linux.

There are some [bundles](https://cozystack.io/docs/bundles/) prepared to install on existing Kubernetes clusters.

As about development Cozystack includes many amazing open-source technologies, one of our moto:

**Collaborate, not compete**

We are proud of our community and closely interact with projects around it. Thus if a feature being developed for the platform could be useful to a upstream project, it should be contributed to upstream project, rather than being implemented within the platform.

We contribute a lot into such projects as Kubernetes, KubeVirt, Cilium, LINSTOR, FluxCD, SeaweedFS, kube-ovn and so on.

> Could you describe the project’s release processes, including major, minor and patch releases.

-  We perform 1-3 feature releases per month, which include the latest features.
-  Additionally, patch releases can be created. These usually contain some bug fixes without introducing new features.

All system components are automatically updated with the installation of a new release.
Cozystack includes mechanisms for performing migrations, so updating Cozystack appears to the user as simply applying a new YAML manifest.

For user-facing services, we do not perform automatic upgrades yet. However, we inform users that an upgrade is available. We allow users to perform updates via the Dashboard, API, or using the GitOps approach.
 but we include older versions  

> Define any specific service dependencies the project relies on in the cluster.

Cozystack covers entrie infrastructure stack:

![Screenshot 2024-08-12 at 16 12 52](https://github.com/user-attachments/assets/189b1696-d003-48ff-8372-b92b6f452f9e)

**Layer 1:**

We don't strictly depend on Talos Linux, but highly recomend it to use. We still provide the oportunity to install Cozystack on different distros. But in this case we don't gurantee that everything will work as expected. Because in this case we can't be sure that system has correct kernel and all the modules enabled (especially DRBD and ZFS)

**Layer 2:**

Consists of system components delivered by [FluxCD](https://fluxcd.io/)
We use:
- [Piraeus](https://piraeus.io/) (LINSTOR) as a default storage. We use it for both cutting the ZFS volumes and enable DRBD replication if needed.
- [Kube-OVN](https://www.kube-ovn.io/) + [Cilium](https://cilium.io/) for the networking and policy enforcement
- [KubeVirt](https://kubevirt.io/) for the virtualization

**Layer 3:**

Consists of system components delivered by [FluxCD](https://fluxcd.io/)

- We use a ordinary Kubernetes operators to manage user's workloads (most of them are mentoined in the first message) these operators perform full lifecycle management for user wirkloads.
- For monitoring we use VictoriaMetrics which has prometeus compatible interface. Also we ship preconfigured Grafana with all the dashboards for these components
- For managing Kubernetes clusters we use Kamaji project and Cluster API

**Layer 4**

User-defined applications can be created via both Cozystack Dashboard (based on kubeapps project) or direcrly in Kubernetes API, and are still managed by FluxCD.

Helm is used to pack all the required YAML-manifests for the operators and provide user a single format for ordering managed services. Thanks to Helm it is easy to extend platform by adding external Helm repository and provide the Helm charts in the same format.


>   Describe the project’s dependency lifecycle policy for each repo.

1. The core project is 
   - https://github.com/aenix-io/cozystack

2. We have two side-projects which are used to simplify the Talos Linux configuration for bare-metal nodes:
    - https://github.com/aenix-io/talos-bootstrap
    - https://github.com/aenix-io/talm

    We provide the examples on using these tools, but not strictly depend on them
    Users are free to use any tool for installing Talos Linux or even perform install on different distro.

3. In the course of developing the Cozystack itself, we also started to develop a common community-driven etcd-operator. We managed to organize a distinct community of 150 memeber and 5-6 consistent contributors withn it to develop this operator. These are people from different organizations whom we have successfully joined together and guided to develop a standard solution that can also be transferred to the CNCF.

    - https://github.com/aenix-io/etcd-operator/

    Currently, we are collaborating with SIGs to create a unified etcd-operator. It is quite possible that our project will be successful and used as a code base, as we have already completed a significant portion of the established roadmap. The working group has [already been established](https://github.com/kubernetes/community/pull/7917). Last week, we had our first meeting.

> Describe all of the signals the project is using or producing, including logs, metrics, profiles and traces. Please include supported formats, recommended configurations and data storage.

In the input we are expecting bare-metal servers, with no OS installed. In the output user gets the interface where they can order managed servcices from their hardware. Such services are:

- Manged Kubernetes (with all the features like dynamic volumes, loadbalancers, cluster-autoscaling)
- Database-as-a-Service: Postgress, MariaDB, Redis, Rabbit, Kafka, NATs, Clickhouse and so on.
- VPN-as-a-service
- Virtual Machines
- HTTP-caching-service
- TCP and HTTP-balancers

All of them are configured to use preconfigured monitoring stack witch is backed by Grafana and Victoria Metrics.
It is possible to run separate monitoring stacks per tenant.

![Screenshot 2024-08-12 at 18 56 05](https://github.com/user-attachments/assets/715c5db6-4cc4-436f-a6f5-95d995838ba3)

**Comment by roberthstrand** [comment] 2024-08-13 13:43
Summary of the key considerations. For more details, see the [review document](https://docs.google.com/document/d/1b-x5l2cY5ys2kUtI3hejIqpQLRxyjGLUKPy_5xhqKNM/edit?usp=sharing).

### Community and Growth
The project is primarily maintained by representatives from Ænix, but there are various contributors from other organizations. The project is relatively new, being around for less than a year, but has already managed to get a healthy number of contributors, GitHub stars and is starting to get some adopters.

The project has been presented at several conferences, including KCD Czech & Slovak. There is a channel on the Kubernetes slack, closely followed up by the maintainers, and they host a weekly community meeting.

### Release Process, Issues and Testing Infrastructure
Cozystack aims to have 1-3 feature releases per month, in addition to path releases when necessary. The project follows semantic versioning, but has no automation for release and testing running yet. There are pull requests covering this, but nothing that has been merged and is in use.

### Project Challenges
The balance between flexibility and opinionated comes to mind. The project should aim to simplify, but not at the cost of flexibility. How can one make sure the various aspects of the platform stack are modular and interchangeable?

### Key Feedback to the Project:

There are some low hanging fruits one could tackle, like adding workflows for release automation and testing. Currently, only one maintainer is set as codeowner, so there is a single point of failure if something happens. After this moves over to a project specific GitHub organization, the governance structure needs to be updated.

I would like to see more documentation in regards to how one can add more services to the project or how to change out the services that come with the project now. It makes sense to allow various platform teams to use Cozystack in a way that fits their organizations needs.

### TAG Recommendation to TOC:
I think the project shows great promise. I have personally worked on creating a similar project, and I know how hard it is to create something that takes into account all the variables of a platform that builds platforms. Cozystack has solved a lot of these issues pretty elegantly, while still keeping simplicity and ease of use in mind.

There is a lot to do when it comes to procedure and governance. After my interactions with the maintainers, I think these changes can be done quickly, and as this is an interesting project there will definitely be many interested potential contributors and maintainers ready to join if it gets accepted as a sandbox project.

In general, I would recommend for the project to be accepted for sandbox. The few issues I have with the project should be easy fixes, and I think they will find a lot of traction as a sandbox project going forward.

**Comment by linsun** [comment] 2024-08-13 16:16
Hi Folks! Thank you for your interest in applying for CNCF sandbox! The TOC has reviewed your application today, and would recommend you to apply for a later date as a CNCF incubation project. We would love you to address the following concerns being discussed in the meeting:
- Separation of the OSS project from business
- More adopters
- Better maintainer & contribution diversity

Thanks much!

**Comment by abangser** [comment] 2024-08-13 19:49
Thanks again for the discussion in the platforms WG (Video attached [here](https://www.youtube.com/watch?v=LSNmi0Y2rhA) for reference)

I know we ran out of time, but one question I have on this proposal is the lack of any cloud native overlaps. I am surprised to see that as I _think_ there are a number of projects that also try to install packages per an operators config. For example, I think [Otomi](https://landscape.cncf.io/?group=projects-and-products&item=platform--paas-container-service--otomi), [KubeFirst](https://landscape.cncf.io/?group=projects-and-products&item=provisioning--automation-configuration--kubefirst) and others seem to be in similar places but CNCF member companies and not projects so no conflict, just curious about the differentiations in a crowded space.

Thanks!

**Comment by kvaps** [comment] 2024-08-13 20:13
Hi @lianmakesthings, thank you for your response. As a self-bootstrapped project, we were hoping that CNCF could help us address these shortcomings :)

> We would love you to address the following concerns being discussed in the meeting:
>
>   - Separation of the OSS project from business
>   - More adopters
>   - Better maintainer & contribution diversity
>   - Improved governance.

Is there a recording publicly available? We would like to review it to better understand the topics discussed. This would help us work in this direction and get better to improve our next application.

> would recommend you to apply for a later date as a CNCF incubation project.

What do you mean by that? Is it possible to apply directly for a CNCF Incubation project without going through the Sandbox? Or will our application be considered later in the CNCF Sandbox?

What further steps would you recommend?

**Comment by lianmakesthings** [comment] 2024-08-13 20:32
Hi @kvaps I believe you meant to reply to @linsun?

**Comment by kvaps** [comment] 2024-08-13 20:33
Hi @abangser, thank you for publishing the video. It was great to attend today's Platforms WG meeting.

> I know we ran out of time, but one question I have on this proposal is the lack of any cloud native overlaps. I am surprised to see that as I think there are a number of projects that also try to install packages per an operators config. For example, I think [Otomi](https://landscape.cncf.io/?group=projects-and-products&item=platform--paas-container-service--otomi), [KubeFirst](https://landscape.cncf.io/?group=projects-and-products&item=provisioning--automation-configuration--kubefirst) and others seem to be in similar places but CNCF member companies and not projects so no conflict, just curious about the differentiations in a crowded space.

As for your question, these projects are intended to provide ready configuration for the Kubernetes, their main focus is Kubernetes distribution. We don't compete them as our main focus is to provide managed services.

As for your question, these projects are designed to provide ready configurations for Kubernetes, with their main focus being Kubernetes distribution. We don't see them as competition because our primary focus is on providing managed services.

We can compete with solutions such as:

-    **Virtuozzo Jelastic** - A proprietary solution for providing managed services.
-    **OpenStack** - An open-source virtualization platform for building clouds. They have the Magnum extension for running Kubernetes clusters and various extensions for DB-as-a-Service.
-    **CloudStack** - An open-source virtualization platform with a Kubernetes-as-a-Service feature.
-    **VMware Tanzu** - A Kubernetes-as-a-Service backed by a proprietary virtualization platform. They offer kubeapps dashboard with various Bitnami Helm charts, but these are not managed collectively and do not address the full lifecycle of managed services.
-    **Harvester** - An open-source virtualization platform backed by KubeVirt. They provide Kubernetes-as-a-Service but lack databases and other managed services with full-cycle management.

Currently, CNCF does not have a project that would solve service-providers needs.

**Comment by kvaps** [comment] 2024-08-13 20:33
> Hi @kvaps I believe you meant to reply to @linsun?

Yeah, sorry, fixed that

**Comment by gecube** [comment] 2024-08-14 07:22
Also I want to add that solutions like [Nutanix](https://www.nutanix.com/) also could be recognised like a competitors to Cozystack.

**Comment by linsun** [comment] 2024-08-14 13:21
> Hi @linsun, thank you for your response. As a self-bootstrapped project, we were hoping that CNCF could help us address these shortcomings :)
> 
> > We would love you to address the following concerns being discussed in the meeting:
> > 
> > * Separation of the OSS project from business
> > * More adopters
> > * Better maintainer & contribution diversity
> > * Improved governance.
> 
> Is there a recording publicly available? We would like to review it to better understand the topics discussed. This would help us work in this direction and get better to improve our next application.
> 
> > would recommend you to apply for a later date as a CNCF incubation project.
> 
> What do you mean by that? Is it possible to apply directly for a CNCF Incubation project without going through the Sandbox? Or will our application be considered later in the CNCF Sandbox?
> 
> What further steps would you recommend?

Yes, recording will be published, I will post a link here.  And yes, you can apply directly for incubation without going through sandbox. Istio project did that, for example.

**Comment by linsun** [comment] 2024-08-14 13:59
Hi @kvaps - the recording from yesterday's meeting is out - https://www.youtube.com/watch?v=dFqDK3YtdEA, which should provide you more context of the discussion and some of the concerns the TOC has.  I believe your project is somewhere in the middle.  As far as further steps, I would recommend you focus on the [concerns](https://github.com/cncf/sandbox/issues/87#issuecomment-2286633339) raised by the TOC members and drive more adoptions for your project. 

Some resources you may find useful:
https://github.com/cncf/toc/blob/main/process/project-stages.png
https://github.com/cncf/toc/tree/main/process#applying-to-become-an-incubating-or-graduating-project

**Comment by gecube** [comment] 2024-08-14 15:15
@linsun Hi! Thanks for the clarifications. Just one question. Is it correct understanding that we should implement some processes and address the concerns before we will proceed? Or could we go "as is"?

**Closed** 2024-08-20 14:49 UTC
Labels: New, App Delivery
